[package]
name = "gist"
version = "0.1.0"
authors = ["Kenta Sato <tosainu.maple@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
